### ISSUE TITLE
Use DependencyResolver to instancetiate new AggregateRoot

### ISSUE THREAD

**Issue by johnm25** [TylerBrinks/SeekU#1]
Hi Tyler,
I suggest something like this...
 class DomainRepository

 public T GetById<T>(Guid aggregateRootId) where T : AggregateRoot, new()
        {
            var aggregateRoot = _dependencyResolver.Resolve<T>() ?? new T();

The reason is that i need to be able to inject into my impl of the AggregateRoot class

Best Regards,
John

**Comment by TylerBrinks** [comment]
Fine idea.  I'll look into that with the next rev which will replace the generic return type from the bus in favor of strongly typed responses.
